site_name: Legato
pages:
    - Home: index.md
    - Installation: installation.md
    - Routing: routing.md
    - Controllers: controller.md
    - Views: views.md
    - Database: database.md
    - Model: models.md
    - Validation: validation.md
    - Sending Mail: mail.md
    - Legato Console: console.md
    - Upgrade From 1.1.1 to 1.1.2: UPGRADE-1.1.2.md
theme: readthedocs