site_name: Legato
pages:
    - Home: index.md
    - Installation: installation.md
    - Routing: routing.md
    - Controllers: controller.md
    - Views: views.md
    - Database: database.md
    - Model: models.md
    - Sending Mail: mail.md
    - Legato Console: console.md
theme: readthedocs